config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    sign_in: 'users/login',
    sign_out: 'users/logout',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  resources :posts do
    resource :likes, only: :update
  end
  resources :comments, only: [:create, :destroy]
  root 'posts#index'
  get 'profiles/my_posts'
  get '/profiles/:id', to: 'profiles#show', as: 'profile'
end

app/models/post.rb
class Post < ApplicationRecord
  include Dateable
  CATEGORIES = %w[movie sport politic economic science].freeze

  enum category: CATEGORIES

  belongs_to  :user
  has_many    :comments
  has_many    :likes

  mount_uploader :image, ImageUploader

  validates :title, :text, presence: true
  validates :category, inclusion: { in: CATEGORIES }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i(new edit create update destroy)
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json

  def index
    scope = params[:category] || 'all'
    @posts = Post.paginate(page: params[:page], per_page: 5).public_send(scope).order(created_at: :desc)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment = Comment.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: t('.notice') }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: t('.notice') }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: t('.notice') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.fetch(:post, {}).permit(:title, :text, :category, :image)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
  def to_html(text)
    return if text.nil?
    text.gsub(/\*(.*)\*/, '<strong>\1</strong>').html_safe
  end
end

app/views/posts/_form.html.haml
= simple_form_for @post, html: {multipart: true} do |f|
  = f.input :category, collection: Post::CATEGORIES.map { |с| [t("post.category.#{с}"), с] },
                       label: 'Категория',
                       include_blank: 'Выберите категорию'
  = f.input :title,
            label: 'Заголовок',
            required: false
  = f.input :text,
            label: 'Текст',
            required: false, input_html: { rows: '10' }
  .actions
    = yield(f)
    = f.file_field :image, class: 'add-image'

app/views/posts/edit.html.haml
.edit-post
  %h1.text-center Редактировать новость
  = render 'form', post: @post do |f|
    = f.submit 'Сохранить', class: 'btn btn-primary'
    = link_to 'Показать полностью', @post, class: 'btn btn-outline-info'
    = link_to 'Назад', posts_path, class: 'back btn btn-outline-dark'

app/views/posts/index.html.haml
.index-post
  - @posts.each do |post|
    .post.clearfix
      .actions
        - if current_user && (post.user == current_user || current_user.admin?)
          = link_to 'Редактировать', edit_post_path(post),
          class: 'edit btn btn-outline-secondary'
          = link_to 'Удалить', post, method: :delete, data: { confirm: 'Вы уверены?' },
          class: 'delete btn btn-outline-danger'
      %h1= link_to post.title, post_path(post)
      .image-index
      = image_tag post.image.url(:thumb), class: 'rounded float-left thumb' if post.image?
      %p.text-justify= truncate(to_html(post.text), length: 250) { link_to 'Показать полностью', post_path(post) }
    .post-info
      %span.category Категория: #{t("post.category.#{post.category}")}
      %span.date-time Добавлено: #{post.created_date}
      %span.author Автор: #{post.user.name}
    .post-like
      - has_like = current_user&.like?(post) ? 'active-like' : ''
      .btn-like{ class: has_like, data: { post: { id: post.id } } }
        .heart
        %span.like-count
          = post.likes.active_likes_count
= will_paginate @posts

app/views/posts/new.html.haml
.new-post
  = render 'form', post: @post do |f|
    = f.submit 'Добавить', class: 'btn btn-primary'
    = link_to 'Назад', posts_path, class: 'back btn btn-outline-dark'

app/views/posts/show.html.haml
.show-post
  %h1.text-center= @post.title
  .image-show.d-flex.align-items-center.flex-column
    = image_tag @post.image.url(:large), class: 'img-fluid' if @post.image?
  %p.text-justify= to_html(@post.text)

  .post-info
    %span.category Категория: #{t("post.category.#{@post.category}")}
    %span.date-time Добавлено: #{@post.created_date}
    %span.author Автор: #{@post.user.name}

  .post-like
  - has_like = current_user&.like?(@post) ? 'active-like' : ''
  .btn-like{ class: has_like, data: { post: { id: @post.id } } }
    .heart
    %span.like-count
      = @post.likes.active_likes_count

  .actions
    - if current_user && (@post.user == current_user || current_user.admin?)
      = link_to 'Редактировать', edit_post_path(@post), class: 'btn btn-primary'
    = link_to 'Назад', posts_path, class: 'btn btn-outline-dark'


.comments
  %h4 Комментарии
  %hr

  = simple_form_for @comment do |f|
    = f.input :post_id, label: false, input_html: { type: 'hidden', value: @post.id }
    = f.input :text, placeholder: 'Оставьте свой комментарий...',
    label: false, required: false, input_html: { rows: '5' }

    .actions
      = f.submit 'Комментировать', class: 'btn btn-outline-success'

  - @post.comments.order_by_new.each do |comment|
    .panel.panel-primary
      .panel-heading
        = comment.user.name
        = comment.created_date
        - if current_user && (comment.user == current_user || current_user.admin?)
          = link_to comment, method: :delete, data: { confirm: 'Вы уверены?' },
          class: 'delete-comment' do
            %i.fa.fas.fa-times-circle
      .panel-footer
        = comment.text