config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    sign_in: 'users/login',
    sign_out: 'users/logout',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  resources :posts do
    resource :likes, only: :update
  end
  resources :comments, only: [:create, :destroy]
  root 'posts#index'
  get 'profiles/my_posts'
  get '/profiles/:id', to: 'profiles#show', as: 'profile'
end

app/views/layouts/_nav.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-light.fixed-top.shadow-sm
  .container-fluid.col-10
    %a.navbar-brand{:href => "/"}
      = image_tag(asset_path('callisto.png'), class: 'd-inline-block align-top')
    %button.navbar-toggler{'aria-controls' => 'navbarToggleExternalContent',
    'aria-expanded' => 'false',
    'aria-label' =>    'Toggle navigation',
    'data-target' =>   '#navbarToggleExternalContent',
    'data-toggle' =>   'collapse', :type => 'button'}
      %span.navbar-toggler-icon
    #navbarToggleExternalContent.collapse.navbar-collapse
      #navbarSupportedContent.collapse.navbar-collapse
      %ul.nav.navbar-nav.col-11
        %li.view
          = link_to 'Кино', posts_path(category: 'movie')
        %li.sports
          = link_to 'Спорт', posts_path(category: 'sport')
        %li.politic
          = link_to 'Политика', posts_path(category: 'politic')
        %li.economic
          = link_to 'Экономика', posts_path(category: 'economic')
        %li.science
          = link_to 'Наука и техника', posts_path(category: 'science')
      .dropdown
        - if user_signed_in?
          = link_to '#', class: 'nav-link dropdown-toggle',
                         id: 'user-full-name',
                         aria: { expanded: 'false', haspopup: 'true' },
                         data: { toggle: 'dropdown' } do
            = image_tag(asset_path('user.png'), class: 'icon')
            = current_user.name
          .dropdown-menu{ aria: { labelledby: 'dropdownMenu2' } }
            = link_to profile_path(current_user), class: 'dropdown-item' do
              = image_tag(asset_path('settings.png'), class: 'icon')
              = t('shared.navbar.my_account')
            = link_to profiles_my_posts_path, class: 'dropdown-item' do
              = image_tag(asset_path('my_news.png'), class: 'icon')
              = t('shared.navbar.my_posts')
            - if current_user.admin?
              = link_to new_admin_user_session_path, class: 'dropdown-item' do
                = image_tag(asset_path('admin.png'), class: 'icon')
                = t('shared.navbar.admin_panel')
            = link_to destroy_user_session_path, method: :delete, class: 'dropdown-item' do
              = image_tag(asset_path('logout.png'), class: 'icon')
              = t('shared.navbar.logout')
        - else
          = link_to new_user_session_path, class: 'dropdown-item' do
            = image_tag(asset_path('sign-in.png'), class: 'icon')
            = t('shared.navbar.login')

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ content: 'text/html; charset=UTF-8', 'http-equiv': 'Content-Type' }
    %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1.0' }
    %title News Blog
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/nav'
    .container.col-10
      - if notice
        %p.alert.alert-success.text-center#notice= notice
      = yield